### ISSUE TITLE
Getting a traceback in RF Version 4.4b (build 2303061747)

### ISSUE THREAD

**Issue by jeremymickel** [ryanbugden/Eyeliner#16]
********************
Installing 'Eyeliner' report:
  Traceback (most recent call last):
      File "usher.py", line 9, in <module>
      File "/Users/jeremymickel/Library/Application Support/RoboFont/plugins/Eyeliner.roboFontExt/lib/eyelinerRF4_4.py", line 14, in <module>
    TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
  
********************

**Comment by ryanbugden** [comment]
Hi Jeremy, could you try it with the latest beta? An internal pref key changed and Eyeliner adapted.

**Comment by jeremymickel** [comment]
Ha, missed a beta update! Now it works.
